name: masterloop_api
description: Masterloop Api plugin
version: 0.0.1
author: Shovel Maman <sma@masterloop.com>
homepage: https://www.masterloop.com/

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  stomp: ^0.8.0
  dio: ^2.1.13
  masterloop_core:
    path: ../core
