name: masterloop_api
description: Masterloop Api plugin
version: 0.0.1
author: Shovel Maman
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  stomp: ^0.8.0
  dio: ^2.1.0
  masterloop_core:
    path: ../core
  masterloop_core_api:
    path: ../core_api
