name: masterloop_bloc
description: Masterloop Bloc plugin
version: 0.0.1
author: Shovel Maman
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  rxdart: ^0.21.0
  masterloop_core:
    path: ../core
  masterloop_core_bloc:
    path: ../core_bloc
